/**
** Purpose: to randomly select values froma a sql server table
** created on: 20/04/2026
** created by: Alex Newsham
**/

/** step 1: create some dummy data and hold it in memory **/
 declare @tbl_1 table (id int identity(1,1), val_1 varchar(max), val_2 varchar(max), val_3 varchar(max))
 insert into @tbl_1 (val_1, val_2, val_3) 
 values('Active','Azure','Alligator'),
('Adventurous','Black','Alpaca'),
('Agile','Blue','Antelope'),
('Alert','Bronze','Ape'),
('Amusing','Brown','Armadillo'),
('Angry','Burgundy','Baboon'),
('Antic','Cerise','Badger'),
('Athletic','Copper','Bat'),
('Aware','Coral','Bear'),
('Bashful','Cornflour','Bee'),
('Beaming','Crimson','Bison'),
('Beautiful','Cyan','Boar'),
('Big','Emerald','Buffalo'),
('Bitter','Fuchsia','Butterfly'),
('Blissful','Gold','Cat'),
('Brave','Gray','Caribou'),
('Brilliant','Green','Cheetah'),
('Busy','Indigo','Chicken'),
('Calm','Ivory','Cod'),
('Capable','Jade','Coyote'),
('Cautious','Khaki','Crow'),
('Challenging','Lavendar','Deer'),
('Charming','Lilac','Dinosaur'),
('Cheerful','Lime','Dog'),
('Chilly','Magenta','Dolphin'),
('Chocolatey','Maroon','Donkey'),
('Clever','Mauve','Dove'),
('Cloudy','Navy','Duck'),
('Compassionate','Orange','Eagle'),
('Considerate','Olive','Eel'),
('Cozy','Peach','Elephant'),
('Cranky','Purple','Elk'),
('Creative','Red','Emu'),
('Crispy','Ruby','Falcon'),
('Crunchy','Sage','Ferret'),
('Dangerous','Scarlet','Finch'),
('Daring','Sienna','Fish'),
('Dark','Silver','Flamingo'),
('Delicate','Teal','Fly'),
('Delightful','Turquoise','Fox'),
('Ecstatic','Violet','Frog'),
('Elated','White','Gerbil'),
('Empty','Yellow','Giraffe'),
('Endless','Azure','Goose'),
('Engaging','Black','Gorilla'),
('Entertaining','Blue','Grasshopper'),
('Equal','Bronze','Grouse'),
('Exstatic','Brown','Guineapig'),
('Fantastic','Burgundy','Gull'),
('Flexible','Cerise','Hamster'),
('Fluffy','Copper','Hawk'),
('Freezing','Coral','Hedgehog'),
('Frenetic','Cornflour','Heron'),
('Funny','Crimson','Hippopotamus'),
('Furious','Cyan','Hog'),
('Fussy','Emerald','Hornet'),
('Generous','Fuchsia','Horse'),
('Gentle','Gold','Hound'),
('Glad','Gray','Hummingbird'),
('Gleeful','Green','Hyena'),
('Gorgeous','Indigo','Jellyfish'),
('Graceful','Ivory','Kangaroo'),
('Harmonious','Jade','Koala'),
('Icky','Khaki','Lark'),
('Icy','Lavendar','Lemur'),
('Infinite','Lilac','Leopard'),
('Intelligent','Lime','Lion'),
('Jaded','Magenta','Llama'),
('Jolly','Maroon','Magpie'),
('Jovial','Mauve','Mallard'),
('Joyful','Navy','Mole'),
('Joyous','Orange','Monkey'),
('Jumpy','Olive','Moose'),
('Kind','Peach','Mosquito'),
('Kindly','Purple','Mouse'),
('Knowledgeable','Red','Mule'),
('Large','Ruby','Nightingale'),
('Lazy','Sage','Ostrich'),
('Left','Scarlet','Otter'),
('Light','Sienna','Owl'),
('Likely','Silver','Ox'),
('Lovely','Teal','Oyster'),
('Loyal','Turquoise','Panda'),
('Lucky','Violet','Parrot'),
('Lush','White','Penguin'),
('Marvellous','Yellow','Pheasant'),
('Mean','Azure','Pigeon'),
('Minty','Black','Pike'),
('Mysterious','Blue','Platypus'),
('Nervous','Bronze','Porpoise'),
('New','Brown','Possum'),
('Nice','Burgundy','Rabbit'),
('Nimble','Cerise','Raccoon'),
('Novel','Copper','Rat'),
('Optimistic','Coral','Ram'),
('Oval','Cornflour','Raven'),
('Peaceful','Crimson','Reindeer'),
('Petite','Cyan','Rhinoceros'),
('Pleasant','Emerald','Seal'),
('Pleased','Fuchsia','Shark'),
('Polite','Gold','Sheep'),
('Precise','Gray','Snake'),
('Pretty','Green','Sparrow'),
('Proud','Indigo','Spider'),
('Quick','Ivory','Squid'),
('Quiet','Jade','Squirrel'),
('Rainy','Khaki','Swan'),
('Relaxing','Lavendar','Tiger'),
('Restful','Lilac','Tortoise'),
('Right','Lime','Trout'),
('Serene','Magenta','Turkey'),
('Shocking','Maroon','Turtle'),
('Short','Mauve','Walrus'),
('Simple','Navy','Wasp'),
('Skilful','Orange','Weasel'),
('Slow','Olive','Whale'),
('Small','Peach','Wolf'),
('Soothing','Purple','Wombat'),
('Sour','Red','Woodpecker'),
('Sparkling','Ruby','Wren'),
('Speedy','Sage','Yak'),
('Spiky','Scarlet','Zebra')


/** Step 2: select values from table rows at random **/
 select top 10 percent id, val_1, val_2 
 from @tbl_1 
 order by newid() 

 select top 3 id, val_1
 from @tbl_1
 order by newid()